# WARNING: Make sure the project-folder-name is unique on your server!
# You should disable port-exposure in production!

volumes:
    claude_home:

services:
    # docker compose exec -it php_ai claude
    # docker compose exec -it php_ai bash
    php_ai:
        image: ghcr.io/jonaaix/laravel-aio:1.3-php8.5-fpm-claude
        stop_grace_period: 60s
        volumes:
            - ./:/app
            - claude_home:/home/laravel
        environment:
            ENV_DEV: true
            SKIP_LARAVEL_BOOT: true
        restart: no
