# .github/workflows/release.yml
name: Create New Release

on:
    workflow_run:
        workflows:
            - Run Tests
        types:
            - completed

jobs:
    release:
        if: >
            github.event.workflow_run.conclusion == 'success' &&
            startsWith(github.event.workflow_run.head_branch, 'v')  # only tags like v1.2.3
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout tag commit
                uses: actions/checkout@v4
                with:
                    ref: ${{ github.event.workflow_run.head_sha }}

            -   name: Verify tag is on main branch
                run: |
                    git fetch origin main
                    if ! git merge-base --is-ancestor ${{ github.event.workflow_run.head_sha }} origin/main; then
                      echo "Tag commit is not on main branch"
                      exit 1
                    fi

            -   name: Create GitHub Release
                uses: actions/create-release@v1
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                with:
                    tag_name: ${{ github.event.workflow_run.head_branch }}
                    release_name: Release ${{ github.event.workflow_run.head_branch }}
                    body: |
                        New release of the Laravel Patches package. Please see the commit history for changes.
                    draft: false
                    prerelease: false
