# Workflow name
name: Run Tests

# Triggers the workflow on push or pull request events
on: [push, pull_request]

jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: true
            matrix:
                # We explicitly define the test combinations instead of a cross-product.
                # This tests each supported Laravel version against its minimum required PHP version.
                include:
                    # Test Laravel 10
                    - laravel: 10.*
                      php: 8.2 # Minimum in this matrix (actual min is 8.1)
                      testbench: 8.*

                    # Test Laravel 11
                    - laravel: 11.*
                      php: 8.2 # Minimum required for Laravel 11
                      testbench: 9.*

                    # Test Laravel 12 (future-proofing)
                    - laravel: 12.*
                      php: 8.3 # Assumed minimum for Laravel 12
                      testbench: 10.*

        name: P${{ matrix.php }} - L${{ matrix.laravel }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv
                  coverage: none

            - name: Install Composer dependencies
              run: |
                  composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
                  composer update --prefer-stable --prefer-dist --no-interaction --no-progress

            - name: Execute tests with PHPUnit
              run: vendor/bin/phpunit
